---
name: Build pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ${{ vars.RUNNER_IMTF_BASIC }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure AWS Deploy credentials
        uses: aws-actions/configure-aws-credentials@v2
        id: aws-central-resources-credentials
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: get CodeArtifact token
        uses: imtf-group/public-actions/codeartifact-login@v14
        with:
          domain-owner: "028952730777"
          domains: |
            imtf-snapshots: CODEARTIFACT_AUTH_TOKEN_SNAPSHOTS
            imtf-releases: CODEARTIFACT_AUTH_TOKEN_RELEASES

      - name: Build with Maven
        run: ./mvnw --settings ./.mvn/settings.xml clean test
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_CHECKS_DISABLE: true
