name: Qodana
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'apis/**'
      - 'deployment/**'
      - 'Dockerfile*'
      - '.dockerignore'
      - '.gitignore'
      - 'QUESTIONS*'
      - 'TODO*'
      - 'README*'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'apis/**'
      - 'deployment/**'
      - 'Dockerfile*'
      - '.dockerignore'
      - '.gitignore'
      - 'QUESTIONS*'
      - 'TODO*'
      - 'README*'

jobs:
  qodana:
    runs-on: ${{ vars.RUNNER_IMTF_BASIC }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_991025640 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'